export const PRODUCT_SUCCESS = 'PRODUCT_SUCCESS';
export const PRODUCT_FAIL = 'PRODUCT_FAIL';
export const GET_PRODUCT = 'GET_PRODUCT';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM';
export const INCREASE_CART_QTY = 'INCREASE_CART_QTY';
export const DECREASE_CART_QTY = 'DECREASE_CART_QTY';
export const RESTORE_CART = 'RESTORE_CART';
export const RESTORE_TOTAL = 'RESTORE_TOTAL';
export const RESTORE_SCGST = 'RESTORE_SCGST';
export const RESTORE_QTY = RESTORE_QTY;
export const SET_THEME = 'SET_THEME';
export const RESTORE_THEME = 'RESTORE_THEME';
export const RESTORE_TOTAL_QTY = 'RESTORE_TOTAL_QTY';
export const TOTAL_QTY = 'TOTAL_QTY';
export const GET_ACCESSORIES = 'GET_ACCESSORIES';
export const GET_ACCESSORIESTWO = 'GET_ACCESSORIESTWO';
export const GET_ACCESSORIESTHREE = 'GET_ACCESSORIESTHREE';
export const GET_RAWMATERIAL = 'GET_RAWMATERIAL';
export const ORDER_BEGIN = 'ORDER_BEGIN';
export const ORDER_ERROR = 'ORDER_ERROR';
export const ORDER_SUCCESS = 'ORDER_SUCCESS';

export const ADD_TO_CART_ACC = 'ADD_TO_CART_ACC';
export const REMOVE_CART_ITEM_ACC = 'REMOVE_CART_ITEM_ACC';
export const INCREASE_CART_QTY_ACC = 'INCREASE_CART_QTY_ACC';
export const DECREASE_CART_QTY_ACC = 'DECREASE_CART_QTY_ACC';
export const SEARCH_LEAD_MASTER = 'SEARCH_LEAD_MASTER';

export const ADD_TO_CART_RAW = 'ADD_TO_CART_RAW';
export const REMOVE_CART_ITEM_RAW = 'REMOVE_CART_ITEM_RAW';
export const INCREASE_CART_QTY_RAW = 'INCREASE_CART_QTY_RAW';
export const DECREASE_CART_QTY_RAW = 'DECREASE_CART_QTY_RAW';
export const SEARCH_LEAD_MASTER1 = 'SEARCH_LEAD_MASTER1';

export const ADD_TO_ASSTWO = 'ADD_TO_ASSTWO';
export const SEARCH_LEAD_MASTER2 = 'SEARCH_LEAD_MASTER2';
export const REMOVE_CART_ITEM_ASSTWO = 'REMOVE_CART_ITEM_ASSTWO';
export const INCREASE_CART_QTY_ASSTWO = 'INCREASE_CART_QTY_ASSTWO';
export const DECREASE_CART_QTY_ASSTWO = 'DECREASE_CART_QTY_ASSTWO';

export const ADD_TO_ASSTHREE = 'ADD_TO_ASSTHREE';
export const SEARCH_LEAD_MASTER3 = 'SEARCH_LEAD_MASTER3';
export const REMOVE_CART_ITEM_ASSTHREE = 'REMOVE_CART_ITEM_ASSTHREE';
export const INCREASE_CART_QTY_ASSTHREE = 'INCREASE_CART_QTY_ASSTHREE';
export const DECREASE_CART_QTY_ASSTHREE = 'DECREASE_CART_QTY_ASSTHREE';

export const GET_NUMBER = 'GET_NUMBER';
